### ISSUE TITLE
Create a Guide: Product Roadmap

### ISSUE THREAD

**Issue by mariastudnicka** [hackforla/product-management#110]
### Overview
We need to create a guide to making a Product Roadmap so that projects can stay clear and focused on the overall approved mission of the project and know where they are at any given time.

### Special Adoption note
Maria has made a guide that explain roadmaps.  Our goal with the Guides is to get specific about how to make one at Hack for LA.  So interviewing the projects that have done it, and writing up the guidance for that is the primary mission. The material that Maria provided can be used for context.

### Action Items
- [ ] Gather examples of how other projects have done, adding each example as a link in the resources section
   - [ ] Once done, remove the "TG: Gather Examples" label and add the "TG: Draft Template" label
- [ ] Create a draft template, either in markdown format in this issue or a google doc in the [product management google drive](https://drive.google.com/drive/folders/1lO8k_0Z1UejkuRlNMYlUl2xlqgyBmvrF?usp=sharing)
    - [ ] Once done, remove the "TG: Draft Template" label and add the "TG: Create Guide" label
- [ ] Create a guide on how to use the template 
   - [ ] Once done, remove the "TG: Create Guide" label and add the "TG: Review Guide" label
- [ ] Review the guide with product management communities of practice
   - [ ] Once done, remove the "TG: Review Guide" label and add the "TG: Leadership Review" label
- [ ] Present to Hack for LA leadership team for sign off
   - [ ] Once approved, remove the "TG: Leadership Review" label and add the "TG: Place Guide" label
- [ ] Possibly create an issue template on .github 
   - [ ] Include link to template under resources if you add it as a template in .github

### Resources

[Roadmap Guide](https://docs.google.com/document/d/1sZHHfqXoui4zsMQ2l_O3TRIJcXQnyOO-bF-KY9jl4qM/edit)

#### Project that have created roadmaps
- [ ] Open Community Survey
  - [OCS Roadmap](https://docs.google.com/spreadsheets/d/163RPNWPhkeah2OvGCqjByMukYduXk66XY7ZpcpLCzXU/edit#gid=617281993) 
  - Issue: https://github.com/hackforla/open-community-survey/issues/43
- [ ] Internship
  - [Internship Roadmap](https://docs.google.com/spreadsheets/d/1GijHiK_DRmlU8U0fZKsV9cjYhy9h3pZ5_OYQVx_mbgo/edit#gid=1055226176)
  - Issue: https://github.com/hackforla/internship/issues/54
- [ ] HackforLA website
  - [website Roadmap](https://docs.google.com/spreadsheets/d/1g3QQH2qsWGa11KgpvE-RdlhEfqD-8gdw1TJAV0LNzl8/edit#gid=1754442892)
  - Issue: 
- [ ] Guides team
   - [ ] [Guides Roadmap](https://docs.google.com/spreadsheets/d/1xYUlIKsfE2-CeExIQ8i3oLD8pC7hjMTPM2YLSMFA8_s/edit#gid=0)
   - [ ] Issue: https://github.com/hackforla/guides/issues/36

#### Projects that are in process of creating roadmaps
- [ ] 100 Automations
  - [ ] [100 Automations Roadmap](https://docs.google.com/spreadsheets/d/1Lv3aMlsHlycPXunTPjSyZgfH4TFRItk_lBn-keipuBU/edit#gid=0)
  - [ ] Issue: https://github.com/100Automations/Website/issues/473
- [ ] Data Science
  - [ ] Data Science Roadmap
  - [ ] Issue:

**Comment by khushbooshah-PM** [comment]
As requested, added a link for VRMS Product Roadmap. Let me know if any more information is required.

https://docs.google.com/document/d/1BlhtbYBbSBlwSKNFupqUwdtKiUluCErIt0Mr4vNzxlA/edit

**Comment by Olivia-Chiong** [comment]
@mariastudnicka Can you please update

Progress:
Blocks:
Availability:
ETA:

**Comment by mariastudnicka** [comment]
Sorry no progress. I can have a draft of this at the end of the week.

**Comment by Olivia-Chiong** [comment]
@mariastudnicka thanks for the comprehensive work on this. However, there needs to be more HfLA examples. Linking to what has been done but not showcasing it as an example doesn't allow for our community to efficiently work using those templates/examples. Please revise accordingly. Thank you!

**Comment by ExperimentsInHonesty** [comment]
@mariastudnicka checking in with you.  Are you still interested in finishing this issue?  Or should we unassign you?

**Comment by mariastudnicka** [comment]
Thanks for the reminder, Bonnie! That totally fell off my radar. : (
Could you please unassign me?

I’ve been slammed with work.

Maria

**Comment by ExperimentsInHonesty** [comment]
@mariastudnicka I know you are not assigned to this issue anymore but I just wanted to drop in and say I really appreciated your work on this.  It will make an incredible guide after the examples from Hack for LA projects are added.

**Comment by mariastudnicka** [comment]
Thanks so much, Bonnie!
I really appreciate that. : )

**Comment by fchan218** [comment]
<details><summary>Prior version of issue</summary>
<p>

### Overview
We need to create a guide to making a Product Roadmap so that projects can stay clear and focused on the overall approved mission of the project and know where they are at any given time.

### Special Adoption note
Maria has made a guide that explain roadmaps.  Our goal with the Guides is to get specific about how to make one at Hack for LA.  So interviewing the projects that have done it, and writing up the guidance for that is the primary mission. The material that Maria provided can be used for context.

### Action Items
- [ ] Gather examples of how other projects have done, adding each example as a link in the resources section
   - [ ] Once done, remove the "TG: Gather Examples" label and add the "TG: Draft Template" label
- [ ] Create a draft template, either in markdown format in this issue or a google doc in the ~[old product management google drive](https://drive.google.com/drive/folders/1lO8k_0Z1UejkuRlNMYlUl2xlqgyBmvrF?usp=sharing)~ [new product management google drive>Product Management Guides](https://drive.google.com/drive/folders/1u9YOTWevHwEiHP8-r8d00rlqOn6q8e-5?usp=sharing)
    - [ ] Once done, remove the "TG: Draft Template" label and add the "TG: Create Guide" label
- [ ] Create a guide on how to use the template 
   - [ ] Once done, remove the "TG: Create Guide" label and add the "TG: Review Guide" label
- [ ] Review the guide with product management communities of practice
   - [ ] Once done, remove the "TG: Review Guide" label and add the "TG: Leadership Review" label
- [ ] Present to Hack for LA leadership team for sign off
   - [ ] Once approved, remove the "TG: Leadership Review" label and add the "TG: Place Guide" label
- [ ] Possibly create an issue template on .github 
   - [ ] Include link to template under resources if you add it as a template in .github

### Resources

[Roadmap Guide](https://docs.google.com/document/d/1sZHHfqXoui4zsMQ2l_O3TRIJcXQnyOO-bF-KY9jl4qM/edit)

#### Project that have created roadmaps
- [ ] Open Community Survey
  - [OCS Roadmap](https://docs.google.com/spreadsheets/d/163RPNWPhkeah2OvGCqjByMukYduXk66XY7ZpcpLCzXU/edit#gid=617281993) 
  - Issue: https://github.com/hackforla/open-community-survey/issues/43
- [ ] Internship
  - [Internship Roadmap](https://docs.google.com/spreadsheets/d/1GijHiK_DRmlU8U0fZKsV9cjYhy9h3pZ5_OYQVx_mbgo/edit#gid=1055226176)
  - Issue: https://github.com/hackforla/internship/issues/54
- [ ] HackforLA website
  - [website Roadmap](https://docs.google.com/spreadsheets/d/1g3QQH2qsWGa11KgpvE-RdlhEfqD-8gdw1TJAV0LNzl8/edit#gid=1754442892)
  - Issue: 
- [ ] Guides team
   - [ ] [Guides Roadmap](https://docs.google.com/spreadsheets/d/1xYUlIKsfE2-CeExIQ8i3oLD8pC7hjMTPM2YLSMFA8_s/edit#gid=0)
   - [ ] Issue: https://github.com/hackforla/guides/issues/36

#### Projects that are in process of creating roadmaps
- [ ] 100 Automations
  - [ ] [100 Automations Roadmap](https://docs.google.com/spreadsheets/d/1Lv3aMlsHlycPXunTPjSyZgfH4TFRItk_lBn-keipuBU/edit#gid=0)
  - [ ] Issue: https://github.com/100Automations/Website/issues/473
- [ ] Data Science
  - [ ] Data Science Roadmap
  - [ ] Issue: 
</p>
</details>

**Comment by fchan218** [comment]
<details><summary>Assignee, Labels, Project Board Placement, and Milestones for this issue in the Product Repo:</summary>
<p>
<img width="343" alt="Screenshot 2024-10-07 at 3 43 45 PM" src="https://github.com/user-attachments/assets/2ffb54e4-7bbb-4837-b394-f35e7f7513dd">
</p>
</details>

**Comment by fchan218** [comment]
### Files in this issue:
[Roadmap Guide](https://docs.google.com/document/d/1sZHHfqXoui4zsMQ2l_O3TRIJcXQnyOO-bF-KY9jl4qM/edit)
- This file will need to be moved to the knowledgebase-content Google Drive
