### ISSUE TITLE
Create a NEW One Sheet: EMS-Triage Tracker

### ISSUE THREAD

**Issue by Olivia-Chiong** [hackforla/product-management#111]
### Overview
Create the project one sheet so it can be shared with stakeholders and funders.

### Action Items
This project has already been completed so there is no team to speak to
- [x] Review the items available in the GitHub repo and the google drive
- [x] Make a copy of the one sheet template and store in the product management google drive/one sheet revisions
- [x] Setup a meeting with the Bonnie to go over the project and understand the basic project information
- [x] Review one sheet and check off items on the checklist to see what it might be missing.
- [x] Create a draft to review with Bonnie

###
Checklist
- [x] Include project logo (top right)
- [x] Overview
- [x] History and or last 6 months
- [x] Partners
- [ ] Roadmap/next 6 months
- [x] Contact email (footer)
- [x] Github URL (footer)
- [ ] Link to project page on hackforla.org (footer)
- [x] Slack channel (footer)
- [x] Last updated date (footer)
- [x] Hack for LA logo (bottom right) 

### Resources/Instructions
Check issue #3 for sample one sheets
[GitHub Repo](https://github.com/hackforla/ems-triage-tracker)
[Google Drive](https://drive.google.com/drive/u/0/folders/1lhaif6UrGv1BvVJCfCQkvrkbJs5cerNm)
[wiki](https://github.com/hackforla/ems-triage-tracker/wiki/Welcome-to-the-EMS-Triage-Tracker)
[EMS-Triage Tracker one sheet Draft](https://docs.google.com/document/d/1ly8rrgzJIYr6LLZEIZ05LUpaNxQxLgU22Bw6HQAok9Y/edit)

**Comment by Olivia-Chiong** [comment]
@ibrahimakintundek connect with @henlatourrette on how to write a one sheet when the project is completed.

**Comment by DrIffathsultana** [comment]
@henlatourrette 
Hi Henry, I need some help on creating one sheet for the project EMS-Triage Tracker. As this project is completed I am not sure how to complete the sections -Proceed with road map for next 6 months.Please guide me thru on How to write a One-sheet when the project is completed.

**Comment by DrIffathsultana** [comment]
@ExperimentsInHonesty 
Hi Bonnie, I need some guidance on creating a one sheet for the project EMS-Triage Tracker. I went through google drive and resources regarding this project. I would be happy if could go over the project and help me understand the basic project information to gain more clarity. Please let me know your availability next week.

**Comment by DrIffathsultana** [comment]
@Olivia-Chiong 
Progress: I have created a [Draft ](https://docs.google.com/document/d/1ly8rrgzJIYr6LLZEIZ05LUpaNxQxLgU22Bw6HQAok9Y/edit)in google drive and and started researching the projects resources.
Blockers: Communication issues as the project is already completed. I still researching about the project.
Availability: I am available next week mostly after 3 pm.
ETA: Still not sure .

**Comment by Olivia-Chiong** [comment]
@DrIffathsultana Please update the following

- **Progress:** _How much progress have you made on the issue?_
- **Blocks:** _Are you facing any blockers?_
- **Availability:** _How much time do you have to work on it this week?_
- **ETA:** _When do you think it will be completed?_

**Comment by DrIffathsultana** [comment]
@Olivia-Chiong 
Progress: Created a [draft](https://docs.google.com/document/d/1ly8rrgzJIYr6LLZEIZ05LUpaNxQxLgU22Bw6HQAok9Y/edit)
Blocks: Reached out to Henry and Bonnie, waiting for their response.
Availability: Next week anytime after 3 pm.
ETA: Still not sure , need more time to research as the project is already completed.

**Comment by DrIffathsultana** [comment]
I am working on it . Need more time.

**Comment by DrIffathsultana** [comment]
@Olivia-Chiong @ExperimentsInHonesty 
Please review the [Draft](https://docs.google.com/document/d/1ly8rrgzJIYr6LLZEIZ05LUpaNxQxLgU22Bw6HQAok9Y/edit)

**Comment by ExperimentsInHonesty** [comment]
@DrIffathsultana thanks for your work on this.  
- Edits I made:
   - I have removed the partners that were not really involved.  The video was made at a time when we used to thank everyone, even if not directly involve.  Now we have more nuanced ways of thanking partners.
- [ ] Edits that need to be made
   - [ ] Several of the logos including the triage tracker logo are distorted (meaning they were resized but the aspect ratio was not kept).  Please try to fix by finding the originals and reinserting them.
  - [ ] the Project's Goals are not really the project goals.  The original goal of the project was take the concept provided by the stakeholders and turn it into a clickable prototype for submission to the next level of the contest that was being put on by NIST and if the project was chosen for the next level, to use the funds made available to move on to a pilot version of the application.

**Comment by ExperimentsInHonesty** [comment]
I edited the [EMS Triage Tracker one sheet](https://docs.google.com/document/d/1ly8rrgzJIYr6LLZEIZ05LUpaNxQxLgU22Bw6HQAok9Y/edit#) and uploaded a pdf here https://github.com/hackforla/product-management/blob/master/project-one-sheets/EMS-Triage-Tracker-One-Sheet.pdf
And I updated the tracking issue https://github.com/hackforla/product-management/issues/3
