### ISSUE TITLE
Create a Guide/Template: How To Use 1Password’s One-Time Password When Logging In to a Google Account

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/product-management#353]
### Overview
We need to create a guide for how to use 1Password’s one-time password when logging in to a Google account so that users know how to log in to 1Password's one-time password.

### Action Items
- [ ] Gather examples of how other Hack for LA projects have done, adding each example as a link in the resources section. It is really important to annotate as you go in this issue, so that if you have to stop working on the issue, its already up to date with your findings.
   - [ ] Once done, remove the "TG: Gather Examples" label and add the "TG: Draft Template" label
- [ ] Create a draft template, either in markdown format in this issue or a google doc in the [product management google drive>Product Management Guides](https://drive.google.com/drive/folders/1u9YOTWevHwEiHP8-r8d00rlqOn6q8e-5?usp=sharing)
    - [ ] Once done, remove the "TG: Draft Template" label and add the "TG: Create Guide" label
- [ ] Create a guide on how to use the template 
   - [ ] Once done, remove the "TG: Create Guide" label and add the "TG: Review Guide" label
- [ ] Review the guide with product management communities of practice
   - [ ] Once done, remove the "TG: Review Guide" label and add the "TG: Leadership Review" label
- [ ] Present to Hack for LA leadership team for sign off
   - [ ] Once approved, remove the "TG: Leadership Review" label and add the "TG: Place Guide" label
- [ ] Possibly create an issue template on .github 
   - [ ] Include link to template under resources if you add it as a template in .github

### Resources
- Refer to #123 for how to write a guide and the guide template
- Update issue #128 with the name of item you are working

**Comment by JessicaLucindaCheng** [comment]
- Availability: 12 hours
- ETA for first draft: Wed, Dec 14, 2022

**Comment by JessicaLucindaCheng** [comment]
- Gathering Examples: Bonnie told me no projects currently use 1Password's One-Time Password for signing into Google Accounts.

**Comment by Rabia2219** [comment]
@JessicaLucindaCheng 
Hi Jessica,
Thank you so much for initializing this. I need a rough draft for tomorrow and I have started a [guide](https://docs.google.com/document/d/1hL3gYqoV6EWl4bUa2VYLgq0N__CjTvSw4Da2M4x2Hxk/edit#heading=h.xllzjbb7f2a7) already. We can edit/update as needed after the review tomorrow. You can take a look but it's still a WIP.

**Comment by JessicaLucindaCheng** [comment]
Sorry, I didn't realize that you and Bonnie needed the guide done so soon. Your [rough draft](https://docs.google.com/document/d/1hL3gYqoV6EWl4bUa2VYLgq0N__CjTvSw4Da2M4x2Hxk/edit#heading=h.xllzjbb7f2a7) looks good so far. Since you didn't want me to make any edits to the rough draft guide you made until after the review, I went ahead and made a copy of the guide in this folder you made in order to fix some of the images and edit some of the content. The folder with copy of the guide, its slide deck images, and any other assets are in here: https://drive.google.com/drive/folders/1cM8YGek8Xf0mqZd__zcXDHuxlq0S7vx3

**Comment by JessicaLucindaCheng** [comment]
**Tasks**
- [ ] Combine the slide decks
- [ ] Combine the guides
- [ ] Delete the copy of the slide deck and guide
- [ ] Troubleshoot section
  - [ ] (1) Include using time.is to sync time
  - [ ] (3) If it still doesn't work, leave a Slack message in the #admin channel 
- [ ] Write an issue to create a separate how to sync time guide
- [ ] Write an issue to create a separate how to use backup codes guide

**Comment by JessicaLucindaCheng** [comment]
- Progress: First draft is done but I still need to move items into a separate guide.
- Blockers: Not a blocker yet but I do have some questions that do need to be addressed before finalizing the guide
- Availability: 6 hours
- ETA: Wed, Dec 21 for second draft and additional guides that need to be created first drafts: Time Sync Guide and Troubleshooting using 1Password's TOTP Guide

**Tasks**
- [ ] Go through each image and make sure each image adheres to hfla standards using a slide deck
- [ ] Then proofread guide
- [ ] Check it adheres to guidelines in https://github.com/hackforla/admin/issues/31
- [ ] Troubleshoot section (will eventually be replaced with a link to a guide)
  - [ ] (1) Include using time.is to sync time
  - [ ] (3) If it still doesn't work, leave a Slack message in the #admin channel 
- [ ] Write an issue to create a separate how to sync time guide
- [ ] Write an issue to create a separate how to use backup codes guide with a Google Account

**Comment by JessicaLucindaCheng** [comment]
- Progress: First draft is done but I still need to move some items into a separate guide.
- Blockers: Not a blocker yet but I do have some questions that do need to be addressed before finalizing the guide
- Availability: 6 hours
- ETA: Wed, Dec 21, 2022 for second draft and additional guides that need to be created first drafts: Time Sync Guide and Troubleshooting using 1Password's TOTP Guide

**Tasks**
- [x] Go through each image and make sure each image adheres to hfla standards using a slide deck
- [ ] Then proofread guide
- [ ] Check it adheres to guidelines in https://github.com/hackforla/admin/issues/31
- [ ] Troubleshoot section (will eventually be replaced with a link to a guide)
  - [ ] (1) Include using time.is to sync time
  - [ ] (3) If it still doesn't work, leave a Slack message in the #admin channel 
- [x] Write an issue to create a separate how to sync time guide --> Issue written. See #354 
- [ ] Write an issue to create a separate how to use backup codes guide with a Google Account

**Comment by JessicaLucindaCheng** [comment]
- Progress: Finalized the guide
- Blockers: None
- Availability: Will update if it needs edits after it is reviewed
- ETA: Will update on if it needs edits after it is reviewed

**Comment by JessicaLucindaCheng** [comment]
@Rabia2219 @ExperimentsInHonesty I have updated the screenshots as requested and made some edits to make some of the wording more inclusive. I think the guide is ready for a final review. Let me know if you need anymore edits in this guide. 
Here is a link to the guide: [_Guide: Log into a Google Account with 2-Step Verification Using 1Password_](https://docs.google.com/document/d/1hL3gYqoV6EWl4bUa2VYLgq0N__CjTvSw4Da2M4x2Hxk/edit#)

**Comment by fchan218** [comment]
<details><summary>Prior version of issue</summary>
<p>
### Overview
We need to create a guide for how to use 1Password’s one-time password when logging in to a Google account so that users know how to log in to 1Password's one-time password.

### Action Items
~- [ ] Gather examples of how other Hack for LA projects have done, adding each example as a link in the resources section. It is really important to annotate as you go in this issue, so that if you have to stop working on the issue, its already up to date with your findings.~
   ~- [ ] Once done, remove the "TG: Gather Examples" label and add the "TG: Draft Template" label~
~- [ ] Create a draft template, either in markdown format in this issue or a google doc in the [product management google drive>Product Management Guides](https://drive.google.com/drive/folders/1u9YOTWevHwEiHP8-r8d00rlqOn6q8e-5?usp=sharing)~
    ~- [ ] Once done, remove the "TG: Draft Template" label and add the "TG: Create Guide" label~
- [x] Create a guide on how to use the template 
   - [x] Once done, remove the "TG: Create Guide" label and add the "TG: Review Guide" label
- [ ] Review the guide with product management communities of practice
   - [ ] Once done, remove the "TG: Review Guide" label and add the "TG: Leadership Review" label
- [ ] Present to Hack for LA leadership team for sign off
   - [ ] Once approved, remove the "TG: Leadership Review" label and add the "TG: Place Guide" label
~- [ ] Possibly create an issue template on .github~
  ~- [ ] Include link to template under resources if you add it as a template in .github~
- [ ] Update issue hackforla/product-management#128 with the name of item you are working

### Resources
- Refer to hackforla/product-management#123 for how to write a guide and the guide template
- Update issue hackforla/product-management#128 with the name of item you are working
- Files for _Guide: Log into a Google Account with 2-Step Verification Using 1Password_ 
  - [Folder](https://drive.google.com/drive/folders/11yhbGn93ygs1rH4Ss8aXLzmdRaA2ygYV)
    - [Guide](https://docs.google.com/document/d/1hL3gYqoV6EWl4bUa2VYLgq0N__CjTvSw4Da2M4x2Hxk/edit#)
    - [Graphics and Annotations slide deck](https://docs.google.com/presentation/d/1b5ZJndqHLxqKwlzpo02QwhSFot7sp8CTV_ejxJud-_0/edit#slide=id.g1acd6c9a8cd_0_115)
    - [Header](https://docs.google.com/drawings/d/1drjr2R2whxx6YICV3M_FcK4_Br9AJ9JYnVLgykXCsWE/edit)

### Notes
- Gathering Examples: Bonnie told me no projects currently use 1Password's One-Time Password for signing into Google Accounts. Therefore, there is no examples to gather.
- Draft Template: There is no template to be created because this is a guide for how to use 1Password's one-time password when signing in to a Google account.
</p>
</details>

**Comment by fchan218** [comment]
<details><summary>Assignee, Labels, Project Board Placement, and Milestones for this issue in the Product Repo:</summary>
<p>


![Screenshot 2024-09-26 at 3 24 45 PM](https://github.com/user-attachments/assets/14db52a3-4f6e-4f17-86be-b82a16c2a46b)

</p>
</details>

**Comment by fchan218** [comment]
### Files in this Issue:

https://docs.google.com/document/d/1hL3gYqoV6EWl4bUa2VYLgq0N__CjTvSw4Da2M4x2Hxk/edit#heading=h.c8tc614ce3iu
- This file will need to be moved to the knowledgebase-content Google Drive

**Comment by fchan218** [comment]
@JessicaLucindaCheng  This guide issue is moving to the knowledgebase-content repo. If you would like to maintain edit access to the issue and its associated files, please fill out the [Google Drive Access Form](https://forms.gle/vnKRqprNYJUG5ET69).
